import { BalaiPelatihan } from "@/types/pelatihan";

export const PILIHAN_SUMMARY_AKP = [
    {
        id: '001',
        name: 'Balai Pelatihan KP',
    },
    {
        id: '002',
        name: 'Satuan Pendidikan KP',
    },
    {
        id: '002',
        name: 'Pelabuhan Perikanan',
    },
    {
        id: '003',
        name: 'Kolaborasi DJPT',
    },
    {
        id: '004',
        name: 'Swasta',
    },
]

export const PILIHAN_SUMMARY_KEAHLIAN_AKP = [
    {
        id: '001',
        name: 'Balai Pelatihan KP',
    },
    {
        id: '002',
        name: 'Satuan Pendidikan KP',
    },
]

export const BALAI_PELATIHAN: BalaiPelatihan[] = [
    {
        Id: "BP001",
        Longitude: 109.15246944603237,
        Latitude: -6.854096593757315,
        Name: "BPPP Tegal",
        Location: "tegal",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Tegal.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Tegal",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "BP002",
        Longitude: 128.1984058812489,
        Latitude: -3.6593469197467323,
        Name: "BPPP Ambon",
        Location: "ambon",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Ambon.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Ambon",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "BP003",
        Longitude: 114.42107402176605,
        Latitude: -8.071680308693933,
        Name: "BPPP Banyuwangi",
        Location: "banyuwangi",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Banyuwangi.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Banyuwangi",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "BP004",
        Longitude: 125.2127379923902,
        Latitude: 1.4584143381978947,
        Name: "BPPP Bitung",
        Location: "bitung",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Bitung.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Bitung",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "BP005",
        Longitude: 98.60778803618938,
        Latitude: 4.365581800690166,
        Name: "BPPP Medan",
        Location: "medan",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Medan.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Medan",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    // {
    //     Id: "SP006",
    //     Longitude: 98.60778803618938,
    //     Latitude: 4.365581800690166,
    //     Name: "Politeknik AUP Jakarta",
    //     Location: "medan",
    //     Description: "Balai Pelatihan dan Penyuluhan Perikanan Medan.",
    //     FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Medan",
    //     KepalaBalaiPelatihan: "",
    //     Image: "",
    // },
];

export const PELABUHAN_PERIKANAN: BalaiPelatihan[] = [
    {
        Id: "BP001",
        Longitude: 109.15246944603237,
        Latitude: -6.854096593757315,
        Name: "PPS Nizam Zachman Jakarta",
        Location: "tegal",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Tegal.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Tegal",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "BP002",
        Longitude: 128.1984058812489,
        Latitude: -3.6593469197467323,
        Name: "PPS Cilacap",
        Location: "ambon",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Ambon.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Ambon",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "BP003",
        Longitude: 114.42107402176605,
        Latitude: -8.071680308693933,
        Name: "PPN Brondong",
        Location: "banyuwangi",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Banyuwangi.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Banyuwangi",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "BP004",
        Longitude: 125.2127379923902,
        Latitude: 1.4584143381978947,
        Name: "PPN Karangantu",
        Location: "bitung",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Bitung.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Bitung",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "BP005",
        Longitude: 98.60778803618938,
        Latitude: 4.365581800690166,
        Name: "PPN Palabuhan Ratu",
        Location: "medan",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Medan.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Medan",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "SP006",
        Longitude: 98.60778803618938,
        Latitude: 4.365581800690166,
        Name: "PPN Pangembengan",
        Location: "medan",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Medan.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Medan",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "SP006",
        Longitude: 98.60778803618938,
        Latitude: 4.365581800690166,
        Name: "PPN Pekalongan",
        Location: "medan",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Medan.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Medan",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "SP006",
        Longitude: 98.60778803618938,
        Latitude: 4.365581800690166,
        Name: "PPN Prigi",
        Location: "medan",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Medan.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Medan",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "SP006",
        Longitude: 98.60778803618938,
        Latitude: 4.365581800690166,
        Name: "PPN Ternate",
        Location: "medan",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Medan.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Medan",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "SP006",
        Longitude: 98.60778803618938,
        Latitude: 4.365581800690166,
        Name: "PPP Untia",
        Location: "medan",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Medan.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Medan",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
    {
        Id: "SP006",
        Longitude: 98.60778803618938,
        Latitude: 4.365581800690166,
        Name: "PPP Sebatik",
        Location: "medan",
        Description: "Balai Pelatihan dan Penyuluhan Perikanan Medan.",
        FullName: "Balai Pelatihan dan Penyuluhan Perikanan (BPPP) Medan",
        KepalaBalaiPelatihan: "",
        Image: "",
    },
];