export const wilayahPukakp: { wilayah: string, tempat: string }[] = [
    { wilayah: "Aceh", tempat: "Tempat PUKAKP Wilayah I" },
    { wilayah: "Medan (BPPP Medan)", tempat: "Tempat PUKAKP Wilayah II" },
    { wilayah: "Lampung", tempat: "Tempat PUKAKP Wilayah III" },
    { wilayah: "DKI Jakarta (Poltek AUP Jakarta)", tempat: "Tempat PUKAKP Wilayah IV" },
    { wilayah: "Tegal (BPPP Tegal)", tempat: "Tempat PUKAKP Wilayah V" },
    { wilayah: "Tegal (SUPM Tegal)", tempat: "Tempat PUKAKP Wilayah VI" },
    { wilayah: "Banyuwangi (BPPP Banyuwangi)", tempat: "Tempat PUKAKP Wilayah VII" },
    { wilayah: "Kupang (Poltek KP Kupang)", tempat: "Tempat PUKAKP Wilayah VIII" },
    { wilayah: "Pontianak (SUPM Pontianak)", tempat: "Tempat PUKAKP Wilayah IX" },
    { wilayah: "Bitung (BPPP Bitung)", tempat: "Tempat PUKAKP Wilayah X" },
    { wilayah: "Bitung (Poltek KP Bitung)", tempat: "Tempat PUKAKP Wilayah XI" },
    { wilayah: "Ambon (BPPP Ambon)", tempat: "Tempat PUKAKP Wilayah XII" },
    { wilayah: "Ambonn (SUPM Ambon)", tempat: "Tempat PUKAKP Wilayah XIII" },
    { wilayah: "Bone (Poltek KP Bone)", tempat: "Tempat PUKAKP Wilayah XIV" },
    { wilayah: "Sorong (Poltek KP Sorong)", tempat: "Tempat PUKAKP Wilayah XV" },
    { wilayah: "Sorong (SUPM Sorong)", tempat: "Tempat PUKAKP Wilayah XVI" },
];
