import './css/style.css'

import { Inter, Plus_Jakarta_Sans } from 'next/font/google'

import localFont from 'next/font/local'

import Header from '@/components/ui/header'
import Banner from '@/components/banner'

const myFont = localFont({
  src: './font/calsans.ttf',
  variable: '--font-calsans',
})

const inter = Plus_Jakarta_Sans({
  subsets: ['latin'],
  variable: '--font-inter',
  display: 'swap',
})

export const metadata = {
  title: 'E-Laut Kementerian Kelautan dan Perikanan RI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${myFont.variable} antialiased bg-white text-gray-900 tracking-tight`}
      >
        <div className="flex flex-col min-h-screen overflow-hidden supports-[overflow:clip]:overflow-clip">
          <Header />
          {children}
        </div>
      </body>
    </html>
  )
}
