import React from "react";
import LandingKomiteApproval from "./pages/landing";

export const metadata = {
  title: "Komite Pengesahan Program Diklat Awak Kapal Perikanan",
  description:
    "Komite yang bertanggung jawab untuk mengesahkan Program Pendidikan dan Pelatihan bagi Awak Kapal Perikanan sesuai dengan standar Kompetensi Nasional dan Internasional.",
  icons: ["/lembaga/logo/logo-sertifikasi-akp.png"],
  keywords: [
    "Komite Pengesahan Program Diklat Awak Kapal Perikanan",
    "Program Diklat Awak Kapal Perikanan",
    "Pendidikan dan Pelatihan Awak Kapal Perikanan",
    "Komite Pengesahan",
    "sertifikasi awak kapal",
    "dpkakp",
    "diklat perikanan",
    "audit",
    "monitoring",
    "evaluasi",
    "quality assurance",
    "compliance",
    "assurance",
    "inspeksi",
    "ankapin I",
    "ankapin II",
    "upgrading skk 60 mil",
    "ANKAPIN-I",
    "ANKAPIN-II",
    "ANKAPIN-III",
    "ATKAPIN-I",
    "ATKAPIN-II",
    "ATKAPIN-III",
    "Ahli Nautika Kapal Penangkap Ikan Tingkat 1",
    "Ahli Nautika Kapal Penangkap Ikan Tingkat 2",
    "Ahli Nautika Kapal Penangkap Ikan Tingkat 3",
    "Ahli Teknika Kapal Penangkap Ikan Tingkat 1",
    "Ahli Teknika Kapal Penangkap Ikan Tingkat 2",
    "Ahli Teknika Kapal Penangkap Ikan Tingkat 3",
    "BSTF I",
    "BSTF II",
    "Basic Safety Training Fisheries Tingkat I",
    "Basic Safety Training Fisheries Tingkat II",
    "SKN",
    "Sertifikasi Kecakapan Nelayan",
    "SKPI",
    "Sertifikasi Keterampilan Penangkapan Ikan",
    "SOPI",
    "Surat Operator Penangkapan Ikan",
    "approval",
    "surveillance",
    "audit program",
    "monitoring program",
    "Rating",
    "E-LAUT",
    "Kepelautan",
    "Nahkoda",
    "Ahli Kapal",
    "Awak Kapal Perikanan",
    "Direktorat Jenderal Perikanan Tangkap",
    "DJPT",
    "Pengesahan Program Diklat",
    "AKAPI",
    "Aplikasi Diklat Awak Kapal Perikanan",
    "Kelautan dan Perikanan",
    "Ahli Nautika",
    "Ahli Teknika",
    "STCWF-95",
    "STCWF",
  ],

  authors: [
    { name: "Kementrian Kelautan dan Perikanan" },
    {
      name: "Badan Penyuluhan dan Pengembangan Sumber Daya Manusia Kelautan dan Perikanan",
    },
    { name: "Pusat Pelatihan Kelautan dan Perikanan" },
  ],

  publisher: "Kementrian Kelautan dan Perikanan",
  url: "/dpkakp/logo.png",
  referrer: "origin-when-cross-origin",
  type: "website",
  robots: "index, follow",
  og: {
    title: "Komite Pengesahan Program Diklat Awak Kapal Perikanan",
    description:
      "Komite yang bertanggung jawab untuk mengesahkan Program Pendidikan dan Pelatihan bagi Awak Kapal Perikanan sesuai dengan standar Kompetensi Nasional dan Internasional.",
    type: "website",
    url: "/dpkakp/logo.png",
    image: "/dpkakp/logo.png",
  },
  twitter: {
    card: "summary_large_image",
    title: "Komite Pengesahan Program Diklat Awak Kapal Perikanan",
    description:
      "Komite yang bertanggung jawab untuk mengesahkan Program Pendidikan dan Pelatihan bagi Awak Kapal Perikanan sesuai dengan standar Kompetensi Nasional dan Internasional.",
    image: "/dpkakp/logo.png",
  },
};

export default function page() {
  return <LandingKomiteApproval />;
}
